/**
 * ISubmissionRepository — persistence contract for student submissions
 * (RFC 0020 section 11). Speaks in plain records and outcomes: no D1, no SQL
 * result shapes, no `meta.changes`. Quota and move guards are atomic in the
 * adapter; a refusal is a typed result, never an exception.
 */
import type { Entities } from '../types/entities';
import type { CursorPage, Paged } from './i-note-repository';

// ── Cursor pagination ───────────────────────────────────────────────────────
// Keyset pagination is shared with student notes (RFC 0016): `CursorPage` and
// `Paged` are declared once in `i-note-repository` and reused here, since two
// modules re-exported by `ports/index.ts` with the same names would be an
// ambiguous export. The opaque cursor string is encoded and decoded by the
// route-layer helper; the repository only ever sees the decoded key.

// ── Records ─────────────────────────────────────────────────────────────────

/** One `topic_submissions` row as the adapter returns it (timestamps ISO-8601). */
export interface SubmissionRecord {
  id: string;
  topicNodeId: string;
  authorId: string;
  /** Joined from `users.name`. */
  authorName: string;
  title: string;
  description: string;
  /** `submissions/{authorId}/{uuid}-{name}`; null once removed by staff. */
  storageKey: string | null;
  originalName: string;
  contentType: string;
  sizeBytes: number;
  status: Entities.Config.SubmissionStatus;
  visibility: Entities.Config.ShareVisibility;
  sharedAt: string | null;
  moderatedAt: string | null;
  moderatedBy: string | null;
  removedAt: string | null;
  removedBy: string | null;
  /** Joined from `users.name` of `removed_by`; null when not removed or the staff account is gone. */
  removedByName: string | null;
  createdAt: string;
  updatedAt: string;
}

/** A record plus its topic's title — for "My demonstrations" and the staff per-student list. */
export interface AuthoredSubmissionRecord extends SubmissionRecord {
  topicTitle: string;
}

// ── Inputs ──────────────────────────────────────────────────────────────────

/** Everything the quota-guarded insert writes. The row starts `pending`. */
export interface CreatePendingSubmission {
  /** Generated by the controller, which also builds `storageKey` from it. */
  id: string;
  topicNodeId: string;
  authorId: string;
  title: string;
  /** Already sanitised; '' when absent. */
  description: string;
  storageKey: string;
  originalName: string;
  contentType: string;
  sizeBytes: number;
  visibility: Entities.Config.ShareVisibility;
}

/** The two limits checked in the same statement as the insert (effective config values). */
export interface SubmissionQuota {
  perTopicMax: number;
  storagePerStudentBytes: number;
}

/** A student's current usage; `removed` rows excluded, `pending` rows included. */
export interface SubmissionUsage {
  /** Pending + ready rows on the given topic (0 when no topic was given). */
  topicCount: number;
  /** Sum of `size_bytes` of pending + ready rows across all topics. */
  bytes: number;
}

/**
 * Last-write-wins metadata edit. Omitted fields are untouched. Setting
 * `visibility: 'shared'` stamps `sharedAt`; `'private'` clears it.
 */
export interface SubmissionMetaPatch {
  title?: string;
  description?: string;
  visibility?: Entities.Config.ShareVisibility;
}

// ── Move (RFC 0020 section 6) ───────────────────────────────────────────────

export type MoveRefusalReason = 'quota' | 'not_found' | 'not_ready' | 'same_topic';

export interface MoveRefusal {
  id: string;
  reason: MoveRefusalReason;
}

/** Partial success is normal; request order is preserved in both arrays. */
export interface MoveResult {
  moved: SubmissionRecord[];
  refused: MoveRefusal[];
}

// ── Listing ─────────────────────────────────────────────────────────────────

/** `all` is staff-only; the controller validates it against roles, the repository never widens it. */
export type SubmissionListScope = 'mine' | 'class' | 'all';

export interface ListSubmissionsByTopicOptions {
  viewerId: string;
  scope: SubmissionListScope;
  /**
   * The label's SUBMISSIONS_SHARING_ENABLED. When false, `class` returns no rows
   * (a read-time filter — rows are never rewritten). Ignored by `mine` and `all`.
   */
  sharingEnabled: boolean;
  page: CursorPage;
}

/** `self`: the author's own rows in every status. `staff`: ready + removed only. */
export type AuthorListScope = 'self' | 'staff';

export interface ListSubmissionsByAuthorOptions {
  scope: AuthorListScope;
  page: CursorPage;
}

/** Counts behind the Demonstrations button and the summary endpoint. */
export interface TopicSubmissionSummary {
  /** Viewer's own non-removed rows on the topic. */
  mine: number;
  /** Shared ready rows on the topic (the controller zeroes it when sharing is off). */
  class: number;
  /** Every ready + removed row on the topic (exposed to staff only). */
  total: number;
}

// ── Port ────────────────────────────────────────────────────────────────────

export interface ISubmissionRepository {
  findById(id: string): Promise<SubmissionRecord | null>;
  /** Quota-guarded insert; null when a quota refused it. */
  createPending(p: CreatePendingSubmission, q: SubmissionQuota): Promise<SubmissionRecord | null>;
  usage(authorId: string, topicNodeId?: string): Promise<SubmissionUsage>;
  markReady(id: string): Promise<SubmissionRecord>;
  updateMeta(id: string, patch: SubmissionMetaPatch): Promise<SubmissionRecord>;
  /** Batched conditional moves, in order; resets visibility to private, keeps moderation. */
  move(authorId: string, ids: string[], targetTopicId: string, perTopicMax: number): Promise<MoveResult>;
  /** Hard delete of the row (the caller deletes the object first). */
  delete(id: string): Promise<void>;
  /** Tombstone: status removed, storage key null, description '', private. */
  markRemoved(id: string, adminId: string): Promise<SubmissionRecord>;
  /** Newest first (`created_at` for mine/all, `shared_at` for class), keyset-paginated. */
  listByTopic(topicNodeId: string, opts: ListSubmissionsByTopicOptions): Promise<Paged<SubmissionRecord>>;
  topicSummary(topicNodeId: string, viewerId: string): Promise<TopicSubmissionSummary>;
  listByAuthor(authorId: string, opts: ListSubmissionsByAuthorOptions): Promise<Paged<AuthoredSubmissionRecord>>;
  /** staffId → set moderation and force private; null → clear. Null result when the id does not exist. */
  setModeration(id: string, staffId: string | null): Promise<SubmissionRecord | null>;
  /** `pending` rows older than `olderThanHours`, oldest first, at most `limit`. */
  listStalePending(olderThanHours: number, limit: number): Promise<SubmissionRecord[]>;
}
